'use strict';

import {store} from '../redux/create';
import {Text} from 'react-native';
import React from 'react';

const es = {
  'Enjoy a new experience': 'استمتع بتجربة جديدة',
  'Please enable your location & notifications to get access to the nearest providers & promotions.': 'رجاء تفعيل خدمة تحديد الموقع و خدمة الاشعارات لضمان معرفة اقرب مقدم خدمة و تلقي العروض.',
  'Discover more.': 'اكتشف المزيد',
  'Quick and easy access to all the services around you, with verified & accredited reviews from other owners.': 'الوصول  بسهولة لمقدمي الخدمات القريبين منك و اراء و تقييم مستخدميين اخرين عن مستوي الخدمة.',
  'Support your Benz community by rating your experience with the service provider.': 'ادعم مجتمع بنز عن طريق تقييم تجربتك مع مقدم الخدمة.',
  'Learn about': 'تعرف على',
  ' About your cluster errors & messages with reasons & recommendations, you can also review others\' experience & add yours.': 'تعرف على رسائل عداد سيارتك الشائعة, الاسباب و الارشدات مع الاطلاع علي تجارب الآخرين المماثلة كما يمكنك إضافة تجربتك الشخصية.',
  'Parts hub': 'سوق قطع الغيار',
  'Get access to the largest spare parts store through simple clicks with verified reviews and feedback from other members.': ' بخطوات بسيطة تسوق عبر أكبر متجر لقطع الغيار و يمكنك ايضا الاطلاع علي تجارب الاخرين.',
  'Get Started': ' ابدأالآن',
  'Continue with Facebook': 'استمر من خلال فيسبوك',
  'Or': 'أو',
  'Email Address or Mobile number': 'رقم الموبايل او البريد الالكتروني',
  'Password': 'كلمة المرور',
  'Login': 'تسجيل الدخول',
  'Forgot your password!': 'نسيت كلمة المرور!',
  'Not registered yet': 'لا تمتلك حساب',
  'Create new account': ' تسجيل حساب جديد',
  'What’s your Benz': 'ايه نوع عربيتك',
  'It’s super quick': 'بسهولة و بسرعة',
  'Scan your Vin Number': 'ادخل رقم تعريف سيارتك',
  'Continue': 'استمرار',
  'Create your account': 'سجل حسابك',
  'One step away': '  بقيت خطوة واحدة',
  'Fill your info Facebook': 'بياناتك بواسطة فيسبوك',
  'Welcome to our Community': 'مرجبا بك معنا',
  'Add your photo': 'اضف صورتك',
  'First name': 'الاسم',
  'Surname': 'اللقب / اسم العائلة',
  'Email Address': 'البريد الالكتروني',
  'Mobile Number': 'رقم الموبايل',
  'I agree to Terms & Conditions': 'اوافق علي الشروط و الاحكام',
  'Register': 'سجل',
  'Scan your Vin': 'ادخل رقم تعريف سيارتك',
  '17 character alpha/numeric serial number unique to each vehicle': 'رقم تعريف السيارة "VIN" وهو مزيج من سبعة عشر رقمًا وحرفًا فريد لكل مركبة',
  'Can’t locate your Vin': 'لا يمكنك تحديد موقع  رقم الشاسيه الخاص بك',
  'Simply locate your Vin': 'ببساطة تحديد موقع "VIN" الخاص بك',
  'in one of 3 places': 'في واحدة من 3 أماكن',
  'Windshield': 'يقع تحت الزجاج الأمامي',
  'Can be viewed through the nearside base of the front windshield in bold white lettering.': 'يمكن رؤيته علي القضيب المعدني الأفقي اسفل الزجاج الأمامي من جهة المحرك',
  'If you find it hard your still can': 'صعب الوصول اليه',
  'Choose your car manually': 'اختر سيارتك يدويًا',
  'Door latch': 'بجانب قفل الباب',
  'Certification label below passenger’s door latch': 'ملصق شهادة أسفل قائم باب السائق أو الراكب',
  'Passenger seat': 'أرضية السيارة',
  'Engraved under right passenger side rear seat': 'يمكنك رأيته محفور اسفل كرسي الركب',
  'Explore all available parts listed': 'استكشف جميع الأجزاء المتاحة ',
  'Enable Notifications': 'تفعيل الاشعارات',
  'Enable Location': 'تفعيل تحديد مكانك',
  'Verify your account': 'قم بتأكيد حسابك',
  'Enter the code that we sent to': 'ادخل الكود الخاص بك',
  'Resend in': 'اعادة الارسال',
  'Search for what are you looking for': 'ابحث عما تريد',
  'Dismiss': 'الغاء او تراجع',
  'Next': 'التالي',
  'Discover top services you want': 'اكتشف افضل الخدمات',
  'try local name to find a service provider': 'جرب الاسم الدارج للوصول لمقدم الخدمة',
  'Your opinion matters': 'رايك يهمنا',
  'Your request sent successfully and our agent will call you shortly':	'تم إرسال طلبك بنجاح  و سوف يقوم أحد مندوبنا بالاتصال بك قريبا',
  'Invite Owners': 'ادعوا الملاك',
  'Home': 'الصفحة الرئيسية',
  'Car Guide': 'دليل السيارات',
  'The Club': 'نادي الاعضاء',
  'Classic member': 'عضوية كلاسيك',
  'Member since': 'مشترك منذ',
  'Most Recent': 'الأحدث ',
  'Open Now': 'يعمل الان',
  'Filters': 'بحث مفصل',
  'Load more': 'اعرض المزيد',
  'Choose': 'اختر',
  'Cancel': 'الغاء',
  'Apply': 'تطبيق',
  'Info': 'البيانات',
  'Reviews': 'التقييمات',
  'Side Door Jam': 'قايم الابواب',
  'Book Now': 'احجز الان',
  'Booking': 'احجز الان',
  'Contacts': 'الاتصال',
  'Offers': 'العروض',
  'Contact now': 'اتصل الان',
  'Be the first to rate this service': 'كن اول مقيم للخدمة',
  'it takes few seconds to share and support others with your experience': 'بثوان بسيطة شارك و ساعد الاخرين برايك',
  'Rate now': 'قيم الان',
  'Your opinion helps other members': 'رايك يساعد اعضاء اخرين',
  'Excellent': 'ممتاز',
  'Fair': 'مقبول',
  'Poor': 'غير مرضى',
  'Sustain a quality service by sharing your opinion': 'حافظ على جودة الخدمات المقدمة من خلال المشاركة برايك',
  'How was it': 'كيف كانت الخدمة',
  'comments or requests': 'اضف اى تعليق او طلب من مقدم الخدمة',
  'Share your opinion': 'شارك برايك',
  'How was your experience': 'ما مدى رضائك',
  'If you find it hard you still can': 'إذا وجدت أنه من الصعب عليك ذلك',
  'Done': 'تم',
  'Thanks': 'شكرا',
  'Your voice matters and helps other members': 'صوتك يهمنا و يساعد ',
  'Rated': 'مقيم',
  'out of': 'من',
  'based on': 'بناء على',
  'owner': 'مالك',
  'Members': 'اعضاء',
  'Members reviews': 'أراء الاعضاء',
  'Most recent': 'الأحدث',
  'Most helpful': 'الاكثر إفادة',
  'Most critical': 'الاكثر تعقيدا',
  'Book your maintenance in advance choose date and time and any comments or requests.': 'اختار المعاد المناسب و اضف اى تعليق او طلب و سنساعدك على تأكيد الموعد',
  'Select date and time': 'اختر التاريخ و الوقت',
  'Send Request': 'ارسل طلبك',
  'Cluster errors': 'اخطاء العداد',
  'Chassis Info': 'معلومات عن الشاسيه',
  'Fues & Relay Location': 'أماكن الفيوزات والكاتوتات',
  'Tire Pressure & Configuration': 'مواصفات وضغوط الاطارات',
  'Services provided': 'قائمة الخدمات',
  'Share with friends':	'شارك مع أصحابك',
  'Part Catalog': 'كتالوج قطع الغيار',
  'Part Catalogue': 'كتالوج قطع الغيار',
  'Search Part Catalogue': 'ابحث باسم قطع الغيار او رقمها',
  'Mototrcode': 'رقم المحرك ',
  'HP': 'عدد الاحصنه',
  'Oil capacity': 'مستوى وضع الزيت للمحرك',
  'Fuel': 'معدل استهلاك البنزين',
  'Acceleration ': 'لتسارع من 0 إلى 100 كم/س',
  'How can we help': 'كيف نستطيع المساعدة',
  'Type the error displayed': 'اكتب الخطأ الظاهر امامك',
  'Thanks for your opinion': 'شكرا لاضافة رايك',
  'Tell us if it works with you?': 'اشرح الحل المناسب ليك',
  'Add your solution to help others': 'اذكر سبب اخر من خلال تجربتك مع الخطأ',
  'Find a service provider': 'بحث عن مقدم خدمة',
  'What do you think it’s?': 'ماهو رأيك ',
  'My Profile': 'حسابي',
  'Choose another model': 'اختر موديل أخر',
  'Update Changes': 'حفظ التعديلات',
  'Change Language': 'تغيير اللغة',
  'Link to Facebook': 'الربط من خلال فيسبوك',
  'Common requested parts for this model': 'قطع غيار تطلب عادة لهذا الموديل',
  'Explore all listed parts': 'تصفح مجموعات قطع الغيار',
  'All': 'الكل',
  'Used': 'مستعمل',
  'New': 'جديد',
  'Featured': 'مميز',
  'Workshops': 'مراكز الخدمة',
  'Part shops': 'محلات قطع غيار',
  'Services': ' كل الخدمات',
  'Facebook': 'فيسبوك',
  'WhatsApp': 'واتساب',
  'Copy Link': 'نسخ الرابط',
  'Share Via': 'شارك عبر',
  'Open From': 'مواعيد العمل من',
  'Days off': 'العطلة الإسبوعيه',
  'Rate your experience': 'قيم الخدمة',
  'Contact Us': 'اتصل بنا',
  'Map': 'خريطة',
  'Offered parts condition': 'حالة القطعة',
  'parts group': 'مجموعات القطع',
  'All Services': 'كل الخدمات',
  'Choose your preferred service': 'اختر الخدمة المرجوة',
  'Service Shops': 'خدمات اخرى',
  'Part Number': 'رقم القطعة',
  'EGP': 'ج.م',
  'Views': 'مشاهدات',
  'Similar Items': 'قطع مماثلة',
  'Displacement': 'السي سي',
  'Engine Code': 'كود المحرك',
  'Horsepower': 'عدد الأحصنة',
  'Engine Oil Capacity': 'مقدار زيت المحرك',
  'Top Speed': 'السرعة القصوى',
  'Fuel Consumption': 'معدل استهلاك البنزين',
  'Acceleration 0-100km/h': 'التسارع من 0 / 100',
  'Tank Capacity': 'سعة خزان الوقود',
  'Tires': 'الإطارات',
  'Text': 'نص',
  'Cluster error': 'اخطاء العداد',
  'Or select your Model': 'أو حدد موديل سيارتك',
  'Engine Type': 'نوع المحرك',
  'Model Year': 'اختر سنة الصنع',
  "What's your Benz": 'حدد نوع سيارتك',
  'Car Engine': 'اختر نوع المحرك',
  'I agree to': 'اوافق على',
  ' Terms & Conditions': 'الشروط و الاحكام',
  'Your request sent successfully, our agent will call you shortly': 'تم إرسال طلبك بنجاح ، سيتم التواصل معك فى اقرب وقت',
  'What might cause such error': 'مسببات الخطأ الدارجة',
  'SMS': 'رسالة نصية (SMS)',
  'Your solution has been submitted successfully': 'تم تقديم الحل الخاص بك بنجاح',
  'No offers here yet': 'لا توجد عروض متاحة حتى الآن',
  'to': 'الي',
  'Monday': 'يوم الإثنين',
  'Tuesday': 'يوم الثلاثاء',
  'Wednesday': 'يوم والأربعاء',
  'Thursday': 'يوم الخميس',
  'Friday': 'يوم الجمعة',
  'Saturday': 'يوم السبت',
  'Sunday': 'يوم الأحد',
  'Looks like this shop doesn’t have any offers yet' : 'يبدو أن هذا المتجر لا يحتوي على أي عروض حتى الآن',
  'km': 'كم',
  'Forget Password ?': 'نسيت كلمة المرور؟',
  'We just need your registered mobile number to send you password reset instructions.': '.نحتاج فقط إلى رقم هاتفك المحمول المسجل لدينا لإرسال تعليمات إعادة تعيين كلمة المرور',
  'Reset Password': ' إعادة تعيين كلمة المرور',
  'Back': 'رجوع ',
  'Successfully send Email with instructions.': '.تم إرسال التعليمات بنجاح على بريدك الإلكتروني',
  'Please Follow Instructions': 'يرجى اتباع التعليمات',
  'Back to login page': 'العودة إلى صفحة تسجيل الدخول',
  'Reset': 'إعادة تعيين',
  'Sort By': 'فرز',
  'Sort By:': 'فرز',
  'location': 'المسافة',
  'Location': 'المسافة',
  'rating': 'التقييم',
  'Rating': 'التقييم',
  'none': 'لأا شيء',
  'Sort Type:': 'طريقة الفرز',
  'ASC': 'تصاعدي',
  'DESC': "تنازلي",
  'Favorites': "المفضلة",
  'No Description Available': 'لا يوجد وصف',
  'Notifications': 'الاشعارات',
  'Memberships': 'العضويات',
  'FIND A SERVICE PROVIDER': 'ادخل اسم مقدم خدمة',
  'The provider is not available during that time': 'مقدم الخدمة غير متوفر في هذا الوقت',
  'Booking is not available': 'مقدم الخدمة غير متوفر في هذا الوقت',
  'Don’t miss the unique opportunity to gain excellent advice and insights from leading car experts – ClubBenz application will help you pamper your car. To download, click on the below link': 'لا تفوت الفرصة و ابدأ الان في الحصول علي جميع المزايا و العروض المقدمة، استمتع بقيادتك و حافظ علي سيارتك من خلال تنزيل ابليكيشن ClubBenz.  لتنزيل الابليكيشن اضغط علي الرابط التالي',
  'Enter Solution...': 'اكتب الحل....',
  'Submit': 'ارسل',
  'Please add country code (Ex: +201 2xx xxx xxx)': 'من فضلك ادخل كود الدولة (مثال: 20x xxxx xxxx+)',
  'Invalid Username and Password': 'يرجي تصحيح رقم الموبايل وكلمة المرور',
  'Please enter phone and password': 'من فضلك ادخل رقم الموبايل وكلمة المرور',
  'Please fill up all details': 'من فضلك قم بملئ كل البيانات',
  'Share Your Opinion': 'شارك برأيك',
  'Share With Friends': 'شارك مع اصدقائك',
  'Services Clubbenz': 'خدمات Clubbenz',
  'Cluster Error': 'اخطاء العداد',
  'Booking Info': 'تفاصيل الحجز',
  'Overall:': 'شامل:',
  'Service Level:': 'مستوي الخدمة:',
  'Value For Money:': 'القيمة المالية:',
  'Cleanliness:': 'النظافة:',
  'Competency:': 'الكفائة:',
  'Ok': 'موافق',
  'Ask Me Later': 'اسألني لاحقا',
  'Clubbenz needs the permission to call so you can reach the provider you want.': 'التطبيق يحتاج الي التصريح لبدء المكالمات',
  'Get permission to call Providers': 'السماح للتطبيق بادارة المكالمات',
  'Address:': 'العنوان',
  'City:': 'المدينة',
  'State:': 'المحافظة',
  'Country:': 'الدولة',
  'No bookings was found': 'لا يوجد حجوزات سابقة',
  'Spread the Word': 'انشر الخبر',
  'My Card': 'بطاقتي',
  'My Bookings': 'حجوزاتي',
  'My Booking': 'حجوزاتي',
  'Favorite Parts': 'المفضلة',
  'Subscribe': 'اشترك',
  'ID Number': 'الرقم القومي',
  'ID Back': 'البطاقة من الخلف',
  'ID Front': 'البطاقة من الامام',
  'License Back': 'رخصة السواقة من الخلف',
  'License Front': 'رخصة السواقة من الامام',
  'All Fields are required': 'جميع الحقول مطلوبة',
  'Delivery Info': 'معلومات الشحن',
  'Payment Info': 'معلومات الدفع',
  'Select a country': 'اختار دولة',
  'Select a state': 'اختار مدينة',
  'Select a city': 'اختار منطقة',
  'Address': 'العنوان',
  'Payment Method:': 'طريقة الدفع',
  'Cash on Delivery': 'الدفع عند الاستلام',
  'Credit': 'كريدت',
  'This method is not available right now.': 'هذه الطريقة غير متوفرة حاليا.',
  'Membership:': 'العضوية: ',
  'Expiring Date:': 'تاريخ الانتهاء:',
  'ID Number:': 'الرقم القومي:',
  'License ID:': 'رقم الرخصة:',
  'Please enter the following details:': 'من فضلك ادخل جميع البيانات التالية:',
  'Confirmation': 'رسالة تأكيدية',
  'Thank you for your feedback-your message is under review': 'شكراً ، سيتم مراجعة رسالتك',
  'Special Service Centers': 'خدمات متخصصة',
  'Expanding the network supports getting the best services': 'مشاركة الاخرين تدعم الحصول علي افضل الخدمات و العروض',
  'License ID': 'رقم الرخصة',
  'New & Used': 'جديد و مستعمل',
  'New Parts': 'جديد',
  'Used Parts': 'مستعمل',
  'Check Vin Number': 'اقرأ رقم تعريف سيارتك',
  'Pick your choice': 'اختار من القائمة',
  'Coming Soon': 'قريبا مزايا خاصة للعضوية',
  'Coming Soon Membership plans': 'قريبا مزايا خاصة للعضوية',
  'Check your internet connection': 'تأكد من خدمة الانترنت على جهازك',
  'The code was sent to your email.': 'تم ارسال الكود الي بريدك الالكتروني.',
  'Clubenz logo and application is fully owned by Trade & Ship Poland and all intellectual property of Clubenz application is Copyrighted in the European Union and subject to EU laws. Any abuse or inappropriate usage of Clubenz shall put users under immediate termination to their account on Clubenz application, website and other properties. By accepting Clubenz terms and conditions users are clearly informed and aware of Clubenz application, website and other properties terms and conditions and all disputes (if any) are subject to Polish Law and EU intellectual property and reserved copyrights. Clubenz aims at excellence in services provided to its customers, those are Clubenz tips to help you enjoy providers services even better. Contracting Clubenz service provider outside the app voids your grantee and keeps you without any quality or cost control, so always use Clubenz for your aimed service needs. We always make sure our service providers are honest and all whilst building our providers network, our criteria of provider’s selection came out of car owners’ recommendations and sound reputation. The aim of the network is improving the quality of services rendered through providers; thus, your opinion really matters to help us to communicate with service providers on your experience to help them to improve and reach your competence. All offers and discounts can be found in the offers and/ or notifications tabs are authenticated through providers, please review offers validity carefully. Advanced booking option is made to ease your car maintenance visit and save your time, thus make sure whilst booking to select dates that suits your availability to serve you and other customers best. Cancelling & No show isn’t welcome at Clubenz. Please note that all data received through Clubenz customers are only and strictly used by Clubenz to help us to render our services appropriately. Any disclosed data are treated as top confidential and wont be disclosed to a third party or used for any marketing purposes through a third party without your consent. Make the most of Clubenz….': 'برجاء العلم بان شعار وتطبيق و العلامة التجارية الخاصةب Clubenz مملوكة بالكامل لشركة Trade & Ship Poland وجميع حقوق الملكية الفكرية و العلامة التجارية الخاصة بتطبيق Clubenz محفوظة الحقوق وتخضع لحماية و قوانين الاتحاد الأوروبي.\n' +
      '\n' +
      'برجاء تجنب أي إساءة أو استخدام غير مناسب لتطبيق Clubenz لكى لا يضع مستخدمى التطبيق للانهاء و الحذف الفوري لحسابهم على تطبيق Clubenz وموقع الويب والممتلكات الأخرى الخاصة ب Clubenz.\n' +
      '\n' +
      'فورقبول الشروط والأحكام الخاصة بتطبيق Clubenz يعتبر مستخدمى التطبيق موافقين و على اتم العلم و بوضوح وإدراك الشروط و الاحكام الخاصة بتطبيق Clubenz وموقع الويب الخاص بالعلامة التجارية Clubenzوتخضع جميع النزاعات (إن وجدت) للقانون البولندي وقوانين الملكية الفكرية للاتحاد الأوروبي.\n' +
      'تهدف Clubenz إلى التميز في الخدمات المقدمة لعملائها ، وهذه نصائح Clubenz لمساعدتك على الاستمتاع بخدمات مقدمي الخدمات بشكل أفضل.\n' +
      'للعميل كل الحق فى التعمل مع مقدمى الخدمات خارج تطبيق Clubenz دون الرجوع على التطبيق و تحت مسئولية العميل و نفضل الاستفادة القصوى للعملاء عن طريق التوصيات و الخصومات المتوفرةعن طريق التطبيق للمحافظة على معايير الجودة و تقليل التكلفة على العملاء من خلال العروض و الخصومات المقدمة من مقدمى الخدمة داخل التطبيق، لذلك استخدم Clubenz دائمًا لتلبية احتياجات الخدمة.\n' +
      'نسعى دائما للتأكد أن مقدمى الخدمات بالتطبيق صادقين وذوى سمعة طيبة و يتم ادراج مقدمى الخدمة بالتطبيق من خلال توصيات مالكي السيارات والسمعة جيدةلمدمى الخدمات.\n' +
      'يهدف التطبيق إلى تحسين جودة الخدمات المقدمة من خلال مقدمي الخدمة ؛ وبالتالي ، فإن رأيك يهمنا حقًا و يساعدتنا على التواصل مع مقدمي الخدمات حول تجربتك لمساعدتهم على تحسين مستوى الخدمة دائما.\n' +
      'يمكن العثور على جميع العروض والخصومات في علامات تبويب العروض و / أو الإشعارات مصادق عليها من خلال مقدمي الخدمة ، يرجى مراجعة صلاحية العروض بعناية.\n' +
      'يتم إجراء خيار الحجز لتسهيل زيارة صيانة سيارتك وتوفير وقتك ، وبالتالي تأكد أثناء الحجز تحديد التواريخ التي تناسب وقتك لخدمتك ولعملائك الآخرين بشكل أفضل. الإلغاء وعدم الحضور بعد الحجز المسبق للصيانة غير مرحب به في Clubenz.\n' +
      'يرجى العلم بأن جميع البيانات التي يتم تلقيها من خلال عملاء Clubenz يتم استخدامها فقط وبشكل صارم من قبل Clubenz لمساعدتنا على تقديم خدماتنا بشكل أفضل ويتم التعامل مع  بيانات الاعضاء بسرية تامة وانه لن يتم التعامل على بيانات الاعضاء او الافصاح عنها لطرف ثالث أو استخدامها لأي أغراض تسويقية من خلال طرف ثالث دون موافقتك.\n' +
      '\n' +
      'أستفد أكثر مع Clubenz\n',
};

export default function __(k ,language) {
  // return k in es && !language.isArabic ? es[k] : k;
  return k in es && (store.getState().language.isArabic == true ? es[k] : k)

}
